# Generated by Django 4.2 on 2024-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tabel_is_check_alter_point_is_anomal'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='x_real',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='name_x',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='name_y',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
