version: "3.3"

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    env_file: ./.env_b
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: littump/backend_project:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./YandexInternalRootCA.crt:/app/redis_server/YandexInternalRootCA.crt
    env_file: ./.env_b
    depends_on:
      - db
  ml:
    image: littump/ml_project:latest
    restart: always
    volumes:
      - ./YandexInternalRootCA.crt:/app/YandexInternalRootCA.crt
    env_file: ./.env_ml
  frontend:
    restart: no
    image: littump/frontend_project:latest
    volumes:
      - ../frontend/:/app/result_build/
    env_file: ./.env_b
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/www/backend/static/
      - media_value:/var/www/backend/media/
      - ../frontend/dist:/usr/share/nginx/html/
    depends_on:
      - frontend
